In [2]:
from sklearn.feature_extraction.text import *
##CountVectorizer,TfidfVectorizer 사용, 특성추출
#CountVectorizer : 각 텍스트에서 단어 출현 횟수를 카운팅한 벡터
#TfidfVectorizer : TF-IDF라는 값을 사용하여 CountVectorizer의 단점을 보완함
#                   빈도수와 역빈도수를 함께 고려

In [16]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do'
]

In [17]:
cv = CountVectorizer()
tfidf = TfidfVectorizer()

In [18]:
print(cv.fit_transform(corpus).toarray())#빈도수기록
#DTM(Document Term Matrix)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]


In [19]:
print(cv.vocabulary_)#사전의 인덱스와 이름을 확인 가능

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [20]:
print(tfidf.fit_transform(corpus).toarray())

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]


In [21]:
print(tfidf.vocabulary_)

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [22]:
##transform 결과를 역으로 추출
cv.inverse_transform(cv.fit_transform(corpus).toarray())

[array(['know', 'love', 'want', 'you', 'your'], dtype='<U6'),
 array(['like', 'you'], dtype='<U6'),
 array(['do', 'should', 'what'], dtype='<U6')]

In [23]:
cv.get_feature_names()#단어이름만 찍어보기.

['do', 'know', 'like', 'love', 'should', 'want', 'what', 'you', 'your']

In [26]:
for i, value in enumerate(cv.get_feature_names()):
    print(i,':',value)

0 : do
1 : know
2 : like
3 : love
4 : should
5 : want
6 : what
7 : you
8 : your


In [27]:
#새로운 문장을 넣어서 어떤 단어들이 들어갔는지 확인해보자.
sentence = ['i like like smile want']

In [30]:
cv.transform(sentence).toarray()

array([[0, 0, 2, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [31]:
#스팸을 나타내는 사전을 만들어주세요
#햄(스팸반대)을 나타내는 사전을 만들어주세요

In [32]:
spam_dict = ['advertise','promotion','sales','hu','special','sale','member',
            'news','buy','free']
ham_dic = ['order','confirm','agree','check','customer','payment','genetal',
           'company','club','send']

In [37]:
##spam 사전 만들기
cv1 = CountVectorizer()
tfidf1 = TfidfVectorizer()
##ham사전 만들기
cv2 = CountVectorizer()
tfidf2 = TfidfVectorizer()


In [53]:
cv1.fit(spam_dict)
tfidf1.fit(spam_dict)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [52]:
cv2.fit(ham_dic)
tfidf2.fit(ham_dic)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [55]:
cv1.vocabulary_

{'advertise': 0,
 'promotion': 6,
 'sales': 8,
 'hu': 3,
 'special': 9,
 'sale': 7,
 'member': 4,
 'news': 5,
 'buy': 1,
 'free': 2}

In [54]:
cv2.vocabulary_

{'order': 7,
 'confirm': 4,
 'agree': 0,
 'check': 1,
 'customer': 5,
 'payment': 8,
 'genetal': 6,
 'company': 3,
 'club': 2,
 'send': 9}

In [40]:
email = [" Promoton! hu good sales sale check payment"]

In [56]:
result1 = cv1.transform(email).toarray() #spam
result1 #2차원

array([[0, 0, 0, 1, 0, 0, 0, 1, 1, 0]], dtype=int64)

In [57]:
result2 = cv2.transform(email).toarray() #ham
result2

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [58]:
spam_feature_list = cv1.get_feature_names()
ham_feature_list = cv2.get_feature_names()

In [59]:
print(spam_feature_list)
print(ham_feature_list)

['advertise', 'buy', 'free', 'hu', 'member', 'news', 'promotion', 'sale', 'sales', 'special']
['agree', 'check', 'club', 'company', 'confirm', 'customer', 'genetal', 'order', 'payment', 'send']


In [61]:
result1[0]

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [46]:
cv2.fit(ham_dic)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [47]:
cv.vocabulary_

{'order': 7,
 'confirm': 4,
 'agree': 0,
 'check': 1,
 'customer': 5,
 'payment': 8,
 'genetal': 6,
 'company': 3,
 'club': 2,
 'send': 9}

In [48]:
result2 = cv.transform(email).toarray()

In [49]:
result2

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [64]:
spam_words_count = sum(result1[0]) ## 스팸에 등장하는 단어의 빈도수
spam_words_count 

3

In [67]:
ham_words_count = sum(result2[0])
ham_words_count

2

In [68]:

if spam_words_count > ham_words_count:
    print('spam mail!!')
else:
    print('ham mail!!')

spam mail!!


In [69]:
##문제1. 한글로 사전을 만들어보고 다음을 스팸인지 아닌지 판단해보세요
email2 = ['광고!! 허경영 good 세일 확인 지불']

In [70]:
##문제2. 감정 분류기
##긍정/부정 사전을 만들어보세요
## input()을 이용해서 문장을 입력받으면, 긍정인지 부정인지 판단해보세요.
## if-df vectorizer를 사용해보세요!

In [71]:
##1.
spam = ['광고','무료','지불','세일','공짜','무조건','뉴스','행사']
ham = ['동의','확인','보냅니다','회사','직원','동료','주문','고객']

In [72]:
#스팸
cv3 = CountVectorizer()
tfidf3 = TfidfVectorizer()#단어빈도의 가중치 조절
#햄
cv4 = CountVectorizer()
tfidf4 = TfidfVectorizer()#단어빈도의 가중치 조절

In [74]:
#스팸단어들(cv3)을 spam객체에 fit 시켜보자.
cv3.fit(spam)
tfidf3.fit(spam)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [78]:
#햄단어들(cv4)을 ham객체에 fit 시켜보자.
cv4.fit(ham)
tfidf4.fit(ham)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [79]:
cv3.vocabulary_#spam

{'광고': 1, '무료': 3, '지불': 6, '세일': 5, '공짜': 0, '무조건': 4, '뉴스': 2, '행사': 7}

In [80]:
cv4.vocabulary_#ham

{'동의': 2, '확인': 6, '보냅니다': 3, '회사': 7, '직원': 5, '동료': 1, '주문': 4, '고객': 0}

In [81]:
#이메일이 스팸인지 아닌지 확인해보자!
email2 = ['광고!! 허경영 good 세일 확인 지불']

In [82]:
result3 = cv3.transform(email2).toarray()#스팸단어 빈도수 채크!
result3

array([[0, 1, 0, 0, 0, 1, 1, 0]], dtype=int64)

In [83]:
result4 = cv4.transform(email2).toarray()#햄단어 빈도수 채크!
result4

array([[0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [84]:
spam_feature_list2 = cv3.get_feature_names()
ham_feature_list2 = cv4.get_feature_names()

In [85]:
print(spam_feature_list2)
print(ham_feature_list2)

['공짜', '광고', '뉴스', '무료', '무조건', '세일', '지불', '행사']
['고객', '동료', '동의', '보냅니다', '주문', '직원', '확인', '회사']


In [86]:
result3[0]

array([0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [87]:
#단어의 빈도수를 세어보자!
spam_words_count2 = sum(result3[0])
spam_words_count2

3

In [88]:
ham_words_count2 = sum(result4[0])
ham_words_count2

1

In [90]:
#스팸인지 햄인지 판별!
if spam_words_count2 > ham_words_count2:
    print('spam mail!!')
else:
    print('ham mail!!')

spam mail!!


In [91]:
##문제2. 감정 분류기
##긍정/부정 사전을 만들어보세요
## input()을 이용해서 문장을 입력받으면, 긍정인지 부정인지 판단해보세요.
## if-df vectorizer를 사용해보세요!

In [92]:
#(1). 사전을 만들기
#(2). input 값을 fit 시키기


In [132]:
feel_good = ['기쁜','행복','웃음','웃다','재미','굿','존잼',
             '꿀','멋진','꿀잼','재미있다','행복하다']
feel_bad = ['나쁜','싫다','노잼','짜증','졸리다','아깝','나쁨',
            '욕','시간아깝다','집가고싶다']

In [144]:
feeling = [input('너의 감정을 이야기해봐: ')]

너의 감정을 이야기해봐: 조금 졸리다. 하지만 재미있고 유익한 시간을 보내고 있어서 행복하다. 꿀잼 ㅎㅎ


In [145]:
#긍
cv5 = CountVectorizer()
tfidf5 = TfidfVectorizer()#단어빈도의 가중치 조절
#부
cv6 = CountVectorizer()
tfidf6 = TfidfVectorizer()#단어빈도의 가중치 조절

In [146]:
#긍정 fit
cv5.fit(feel_good)
tfidf5.fit(feel_good)
#부정 fit
cv6.fit(feel_bad)
tfidf6.fit(feel_bad)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [147]:
cv5.vocabulary_#긍

{'기쁜': 0,
 '행복': 8,
 '웃음': 4,
 '웃다': 3,
 '재미': 5,
 '존잼': 7,
 '멋진': 2,
 '꿀잼': 1,
 '재미있다': 6,
 '행복하다': 9}

In [148]:
cv6.vocabulary_#부

{'나쁜': 0,
 '싫다': 4,
 '노잼': 2,
 '짜증': 8,
 '졸리다': 6,
 '아깝': 5,
 '나쁨': 1,
 '시간아깝다': 3,
 '집가고싶다': 7}

In [149]:
feeling

['조금 졸리다. 하지만 재미있고 유익한 시간을 보내고 있어서 행복하다. 꿀잼 ㅎㅎ']

In [150]:
#feeling은 꼭 list타입 이어야한다.
result5 = cv5.transform(feeling).toarray()#긍정단어 빈도수 채크!
result5

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [151]:
result6 = cv6.transform(feeling).toarray()#부정단어 빈도수 채크!
result6

array([[0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [152]:
feel_good_count = sum(result5[0])
feel_good_count

2

In [153]:
feel_bad_count = sum(result6[0])
feel_bad_count

1

In [154]:
if feel_good_count > feel_bad_count:
    print('긍정')
else:
    print('부정')

긍정
