In [64]:
# 주요 라이브러리 import
import warnings
warnings.filterwarnings(action='ignore')
import time
from IPython.display import Image
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
import sklearn.datasets as data
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [65]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd

In [ ]:
###라벨 인코딩할 컬럼이 1개인 경우

In [3]:
계절 = ['봄','여름','가을','겨울']

In [4]:
#df = index + Series
#Series = index + values(ndarray)

In [5]:
#df에서 하나의 열은 series객체이다.

In [6]:
data = pd.Series(계절)

In [7]:
data

0     봄
1    여름
2    가을
3    겨울
dtype: object

In [9]:
encoder = LabelEncoder()
#여자는 0번 남자는 1번 이런식으로 알아서 바꿔주는 객체 생성.

In [10]:
encoder.fit(data)#인코딩해줄 데이터를 정리개념!#(가을을 2번으로 하고 겨울을 3번으로 하자~)
#어떤것을 어떤 번호로 인코딩해야할지 정하는 역할
#가을,겨울,봄,여름 순으로 0,1,2,3 지정

LabelEncoder()

In [11]:
encoder.classes_

array(['가을', '겨울', '봄', '여름'], dtype=object)

In [16]:
변환할컬럼 = ['가을', '겨울', '봄', '여름', '겨울','봄','여름','봄','여름']


In [18]:
target = pd.Series(변환할컬럼)

In [19]:
encoder.transform(target)

array([0, 1, 2, 3, 1, 2, 3, 2, 3])

In [21]:
target2 = encoder.transform(target)
print(target2, type(target2))

[0 1 2 3 1 2 3 2 3] <class 'numpy.ndarray'>


In [22]:
#inverse:거꾸로 되돌리다.(reverse)
array1 = [1,3,4,5,7,8,9]
list.reverse(array1)
array1

[9, 8, 7, 5, 4, 3, 1]

In [24]:
target3 = encoder.inverse_transform(target2)
target3

array(['가을', '겨울', '봄', '여름', '겨울', '봄', '여름', '봄', '여름'], dtype=object)

In [25]:
##라벨 인코딩할 컬럼이 2~3개인 경우

In [26]:
words = ['apple', 'summer', 'summer', 'spring', 'spring']
hobby = ['book', 'run','talk','coffee','song']

In [28]:
df = pd.DataFrame({'words':words,'hobby':hobby})
df

words   hobby
0   apple    book
1  summer     run
2  summer    talk
3  spring  coffee
4  spring    song

In [29]:
encoder2 = LabelEncoder()

In [30]:
col = df.columns
col

Index(['words', 'hobby'], dtype='object')

In [31]:
#int:객체
#integer:함수를 가질 수 있는 클래스

In [32]:
for c in col:
    df[c] = encoder2.fit_transform(df[c])
    

In [33]:
df

words  hobby
0      0      0
1      2      2
2      2      4
3      1      1
4      1      3

In [36]:
#나이(10, 20, 30): 연속적인 숫자 => 라벨인코딩의 대상이 되지 않음.
#나이대(어린이, 성년, 노년): 연속적인 숫자가 아님 =>라벨인코딩의 대상이 됨. category

In [37]:
##원핫 인코딩! ##
##라벨인코딩: 연속형이 아닌 데이터를 원하는 형태의 숫자로 바꾸어주는 것!
##            1) 연속형이 아닌 데이터를 숫자로 변환: LabelEncodertt사용
##              fit()--transform(),fit_transform()
##            2) 숫자로만 변환하는 경우, 컴퓨터는 연속형 숫자로 오해하여 연산수행하여
##               의도치 않은 결과가 나올 수 있음. 해당됨을 나타나게 하기 위해
##               라벨의 갯수만큼 컬럼을 만들어주고 해당되는 라벨에 표시(1)로 해주는 방법을 사용
##               원핫인코딩



In [38]:
data2 = pd.Series(['apple', 'summer', 'spring', 'summer', 'spring'])
data2

0     apple
1    summer
2    spring
3    summer
4    spring
dtype: object

In [40]:
data2.unique()#3개의 컬럼이 만들어진다.

array(['apple', 'summer', 'spring'], dtype=object)

In [41]:
pd.get_dummies(data2)

apple  spring  summer
0      1       0       0
1      0       0       1
2      0       1       0
3      0       0       1
4      0       1       0

In [44]:
df2 = pd.DataFrame({"words" : ['apple', 'summer', 'summer', 'spring', 'spring'], 
                    "hobby" : ['book', 'run','talk','coffee','song']})
df2

words   hobby
0   apple    book
1  summer     run
2  summer    talk
3  spring  coffee
4  spring    song

In [45]:
pd.get_dummies(df2)

words_apple  words_spring  words_summer  hobby_book  hobby_coffee  \
0            1             0             0           1             0   
1            0             0             1           0             0   
2            0             0             1           0             0   
3            0             1             0           0             1   
4            0             1             0           0             0   

   hobby_run  hobby_song  hobby_talk  
0          0           0           0  
1          1           0           0  
2          0           0           1  
3          0           0           0  
4          0           1           0

In [46]:
pd.get_dummies(df2.loc[:,['words','hobby']])#겟더미스 컬럼 지정해서 여러개 가져오기 가능.

words_apple  words_spring  words_summer  hobby_book  hobby_coffee  \
0            1             0             0           1             0   
1            0             0             1           0             0   
2            0             0             1           0             0   
3            0             1             0           0             1   
4            0             1             0           0             0   

   hobby_run  hobby_song  hobby_talk  
0          0           0           0  
1          1           0           0  
2          0           0           1  
3          0           0           0  
4          0           1           0

In [2]:
df_drink = pd.read_csv('./drinks.csv')
df_drink

country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
0                             0.0        AS  
1                             4.9        EU  
2                             0.7        AF  
3                            12.4        EU  
4                             5.9        AF  
..                            ...       ...  
188                           7.7        SA  
189                           2.0        AS  
190                           0.1        AS  
191                           2.5        AF  
192                           4.7        AF  

[193 rows x 6 columns]

In [3]:
mean = df_drink.mean()

In [4]:
mean

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

In [5]:
df_drink.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [46]:
#cut 함수를 사용해서 3가지로 beer_servings를 분류해 나타냄.
#그리고 라벨인코딩해보자.
df_drink['beer_cat'] = pd.cut(df_drink['beer_servings'],
                                            bins = [0, 76, 188, 376],
                                            include_lowest=True,
                                            labels= ['low','middle','high']
                            )
df_drink['beer_cat'][:5]

0       low
1    middle
2       low
3      high
4      high
Name: beer_cat, dtype: category
Categories (3, object): [low < middle < high]

In [48]:
df_drink.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent', 'beer_cat'],
      dtype='object')

In [49]:
df_drink[:5]

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent beer_cat  
0                           0.0        AS      low  
1                           4.9        EU   middle  
2                           0.7        AF      low  
3                          12.4        EU     high  
4                           5.9        AF     high

In [68]:
data_drink = pd.Series(df_drink['beer_cat'])

In [69]:
encoder_drink = LabelEncoder()

In [70]:
encoder_drink.fit(data_drink)

LabelEncoder()

In [72]:
변환할컬럼 = ['low', 'middle', 'low', 'high']

In [73]:
target = pd.Series(변환할컬럼)

In [74]:
encoder_drink.transform(target)

array([1, 2, 1, 0])

In [75]:
target2 = encoder_drink.transform(target)
print(target2, type(target2))

[1 2 1 0] <class 'numpy.ndarray'>


In [76]:
target3 = encoder_drink.inverse_transform(target2)
target3

array(['low', 'middle', 'low', 'high'], dtype=object)

In [62]:
#beer_cat 컬럼 원핫인코딩
pd.get_dummies( df_drink['beer_cat']).head()

beer_cat  low  middle  high
0           1       0     0
1           0       1     0
2           1       0     0
3           0       0     1
4           0       0     1

In [29]:
#원핫인코딩 특정컬럼
pd.get_dummies(df_drink.loc[:,['country','continent']]).head()
#겟더미스 컬럼 지정해서 여러개 가져오기 가능.

country_Afghanistan  country_Albania  country_Algeria  country_Andorra  \
0                    1                0                0                0   
1                    0                1                0                0   
2                    0                0                1                0   
3                    0                0                0                1   
4                    0                0                0                0   

   country_Angola  country_Antigua & Barbuda  country_Argentina  \
0               0                          0                  0   
1               0                          0                  0   
2               0                          0                  0   
3               0                          0                  0   
4               1                          0                  0   

   country_Armenia  country_Australia  country_Austria  ...  \
0                0                  0                0  ...   
1                0                  0                0  ...   
2                0                  0                0  ...   
3                0                  0                0  ...   
4                0                  0                0  ...   

   country_Venezuela  country_Vietnam  country_Yemen  country_Zambia  \
0                  0                0              0               0   
1                  0                0              0               0   
2                  0                0              0               0   
3                  0                0              0               0   
4                  0                0              0               0   

   country_Zimbabwe  continent_AF  continent_AS  continent_EU  continent_OC  \
0                 0             0             1             0             0   
1                 0             0             0             1             0   
2                 0             1             0             0             0   
3                 0             0             0             1             0   
4                 0             1             0             0             0   

   continent_SA  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 198 columns]

In [26]:
#원핫인코딩 df전체
pd.get_dummies(df_drink).head()

beer_servings  spirit_servings  wine_servings  \
0              0                0              0   
1             89              132             54   
2             25                0             14   
3            245              138            312   
4            217               57             45   

   total_litres_of_pure_alcohol  country_Afghanistan  country_Albania  \
0                           0.0                    1                0   
1                           4.9                    0                1   
2                           0.7                    0                0   
3                          12.4                    0                0   
4                           5.9                    0                0   

   country_Algeria  country_Andorra  country_Angola  \
0                0                0               0   
1                0                0               0   
2                1                0               0   
3                0                1               0   
4                0                0               1   

   country_Antigua & Barbuda  ...  country_Venezuela  country_Vietnam  \
0                          0  ...                  0                0   
1                          0  ...                  0                0   
2                          0  ...                  0                0   
3                          0  ...                  0                0   
4                          0  ...                  0                0   

   country_Yemen  country_Zambia  country_Zimbabwe  continent_AF  \
0              0               0                 0             0   
1              0               0                 0             0   
2              0               0                 0             1   
3              0               0                 0             0   
4              0               0                 0             1   

   continent_AS  continent_EU  continent_OC  continent_SA  
0             1             0             0             0  
1             0             1             0             0  
2             0             0             0             0  
3             0             1             0             0  
4             0             0             0             0  

[5 rows x 202 columns]