In [1]:
import pandas as pd
import numpy as np
import random
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
#사이킷런에 들어있는 보스턴 집값 데이터를 불러오자.
from sklearn import datasets

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [4]:
diabetes = datasets.load_diabetes()
#sklearn.untils.Bunch: dictionary객체로 만들어 놓은 것
type(diabetes)

sklearn.utils.Bunch

In [5]:
diabetes.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [6]:
#문제
X_data = diabetes.data
X_data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [7]:
#답(당뇨병)
y_data = diabetes.target
y_data

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [8]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [9]:
X_data.shape

(442, 10)

In [10]:
y_data.shape

(442,)

In [11]:
#전처리(스캐일링)
scaler = MinMaxScaler()
X_data_scaled = scaler.fit_transform(X_data)
X_data_scaled

array([[0.66666667, 1.        , 0.58264463, ..., 0.28208745, 0.56221737,
        0.43939394],
       [0.48333333, 0.        , 0.14876033, ..., 0.14104372, 0.22244301,
        0.16666667],
       [0.88333333, 1.        , 0.51652893, ..., 0.28208745, 0.49658437,
        0.40909091],
       ...,
       [0.68333333, 1.        , 0.28512397, ..., 0.24964739, 0.30504048,
        0.56060606],
       [0.28333333, 0.        , 0.49586777, ..., 0.39351199, 0.65702021,
        0.40909091],
       [0.28333333, 0.        , 0.0661157 , ..., 0.14104372, 0.46930778,
        0.51515152]])

In [12]:
#y값은 스케일링 하지 않는다.(답이기 때문)
X_train, X_test, y_train, y_test = train_test_split(X_data_scaled, y_data, 
                                                    test_size=0.1, 
                                                    shuffle=True, 
                                                    random_state=11)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(397, 10) (397,)
(45, 10) (45,)


In [13]:
# Layer를 순서대로 쌓아줄 객체 필요 Sequantial
# 각 Layer는 Dense객체
# 심층 신경망
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [14]:
#레이어를 순서대로 쌓을 수 있도록 객체를 생성
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=10))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))##회귀이기 때문에 linear
##회귀일때, 마지막 출력층의 활성화함수

##쌓은 것으로 모델 셋팅을 하세요
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
# 모델에 세팅한 내용을 요약해서 프린트
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1408      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 16)                528       
                                                                 
 dense_4 (Dense)             (None, 1)                 17        
                                                                 
Total params: 12,289
Trainable params: 12,289
Non-trainable params: 0
_________________________________________________________________


In [15]:
history = model.fit(X_train, y_train, epochs=500, batch_size=32, verbose=2)
history

Epoch 1/500
13/13 - 0s - loss: 28971.3945 - mae: 152.3465 - 436ms/epoch - 34ms/step
Epoch 2/500
13/13 - 0s - loss: 28618.0586 - mae: 151.2145 - 12ms/epoch - 921us/step
Epoch 3/500
13/13 - 0s - loss: 27528.4805 - mae: 147.7201 - 14ms/epoch - 1ms/step
Epoch 4/500
13/13 - 0s - loss: 24304.6855 - mae: 136.7323 - 12ms/epoch - 921us/step
Epoch 5/500
13/13 - 0s - loss: 16568.5977 - mae: 106.4903 - 13ms/epoch - 997us/step
Epoch 6/500
13/13 - 0s - loss: 6794.0483 - mae: 65.2698 - 12ms/epoch - 921us/step
Epoch 7/500
13/13 - 0s - loss: 5091.6592 - mae: 60.5730 - 11ms/epoch - 844us/step
Epoch 8/500
13/13 - 0s - loss: 4520.1914 - mae: 56.7264 - 12ms/epoch - 921us/step
Epoch 9/500
13/13 - 0s - loss: 4454.6372 - mae: 55.9086 - 16ms/epoch - 1ms/step
Epoch 10/500
13/13 - 0s - loss: 4314.7373 - mae: 55.7320 - 13ms/epoch - 997us/step
Epoch 11/500
13/13 - 0s - loss: 4183.7319 - mae: 54.8568 - 11ms/epoch - 844us/step
Epoch 12/500
13/13 - 0s - loss: 4108.0679 - mae: 53.9572 - 14ms/epoch - 1ms/step
Epoch 13/

Epoch 101/500
13/13 - 0s - loss: 2782.7681 - mae: 42.8473 - 13ms/epoch - 997us/step
Epoch 102/500
13/13 - 0s - loss: 2753.0488 - mae: 42.4853 - 12ms/epoch - 921us/step
Epoch 103/500
13/13 - 0s - loss: 2756.5063 - mae: 42.5652 - 11ms/epoch - 844us/step
Epoch 104/500
13/13 - 0s - loss: 2750.6641 - mae: 42.5928 - 13ms/epoch - 997us/step
Epoch 105/500
13/13 - 0s - loss: 2731.6543 - mae: 42.3612 - 15ms/epoch - 1ms/step
Epoch 106/500
13/13 - 0s - loss: 2750.1328 - mae: 42.6148 - 13ms/epoch - 997us/step
Epoch 107/500
13/13 - 0s - loss: 2790.5034 - mae: 42.6265 - 10ms/epoch - 767us/step
Epoch 108/500
13/13 - 0s - loss: 2723.8740 - mae: 42.3704 - 10ms/epoch - 767us/step
Epoch 109/500
13/13 - 0s - loss: 2722.1797 - mae: 42.2570 - 11ms/epoch - 844us/step
Epoch 110/500
13/13 - 0s - loss: 2746.2012 - mae: 42.5161 - 9ms/epoch - 690us/step
Epoch 111/500
13/13 - 0s - loss: 2753.8779 - mae: 42.4383 - 10ms/epoch - 767us/step
Epoch 112/500
13/13 - 0s - loss: 2722.1978 - mae: 42.2684 - 9ms/epoch - 690us/s

Epoch 199/500
13/13 - 0s - loss: 2600.4536 - mae: 41.0310 - 9ms/epoch - 690us/step
Epoch 200/500
13/13 - 0s - loss: 2611.0486 - mae: 41.0533 - 10ms/epoch - 767us/step
Epoch 201/500
13/13 - 0s - loss: 2594.9143 - mae: 40.9053 - 10ms/epoch - 767us/step
Epoch 202/500
13/13 - 0s - loss: 2614.4355 - mae: 40.9688 - 10ms/epoch - 767us/step
Epoch 203/500
13/13 - 0s - loss: 2635.8672 - mae: 41.1741 - 9ms/epoch - 690us/step
Epoch 204/500
13/13 - 0s - loss: 2611.3364 - mae: 41.0893 - 10ms/epoch - 767us/step
Epoch 205/500
13/13 - 0s - loss: 2589.4661 - mae: 40.9421 - 9ms/epoch - 690us/step
Epoch 206/500
13/13 - 0s - loss: 2598.6069 - mae: 40.8968 - 9ms/epoch - 704us/step
Epoch 207/500
13/13 - 0s - loss: 2585.5359 - mae: 41.1290 - 11ms/epoch - 844us/step
Epoch 208/500
13/13 - 0s - loss: 2608.7429 - mae: 41.1579 - 9ms/epoch - 690us/step
Epoch 209/500
13/13 - 0s - loss: 2592.5161 - mae: 40.8971 - 10ms/epoch - 767us/step
Epoch 210/500
13/13 - 0s - loss: 2581.2300 - mae: 40.9396 - 11ms/epoch - 844us/st

Epoch 297/500
13/13 - 0s - loss: 2540.2097 - mae: 39.9627 - 10ms/epoch - 767us/step
Epoch 298/500
13/13 - 0s - loss: 2471.4346 - mae: 39.5404 - 9ms/epoch - 690us/step
Epoch 299/500
13/13 - 0s - loss: 2485.7344 - mae: 39.5618 - 10ms/epoch - 767us/step
Epoch 300/500
13/13 - 0s - loss: 2498.6421 - mae: 39.7434 - 10ms/epoch - 767us/step
Epoch 301/500
13/13 - 0s - loss: 2508.3008 - mae: 39.6952 - 10ms/epoch - 767us/step
Epoch 302/500
13/13 - 0s - loss: 2505.5850 - mae: 39.8962 - 10ms/epoch - 760us/step
Epoch 303/500
13/13 - 0s - loss: 2496.5513 - mae: 39.7563 - 10ms/epoch - 767us/step
Epoch 304/500
13/13 - 0s - loss: 2510.8108 - mae: 39.7539 - 10ms/epoch - 767us/step
Epoch 305/500
13/13 - 0s - loss: 2520.8818 - mae: 39.9272 - 10ms/epoch - 767us/step
Epoch 306/500
13/13 - 0s - loss: 2458.0488 - mae: 39.3028 - 9ms/epoch - 690us/step
Epoch 307/500
13/13 - 0s - loss: 2490.4751 - mae: 39.7006 - 9ms/epoch - 690us/step
Epoch 308/500
13/13 - 0s - loss: 2489.1416 - mae: 39.6181 - 9ms/epoch - 690us/s

Epoch 395/500
13/13 - 0s - loss: 2439.3350 - mae: 38.9671 - 9ms/epoch - 690us/step
Epoch 396/500
13/13 - 0s - loss: 2421.8684 - mae: 38.6865 - 9ms/epoch - 690us/step
Epoch 397/500
13/13 - 0s - loss: 2406.7644 - mae: 38.5925 - 11ms/epoch - 844us/step
Epoch 398/500
13/13 - 0s - loss: 2421.6743 - mae: 38.6012 - 10ms/epoch - 767us/step
Epoch 399/500
13/13 - 0s - loss: 2443.3948 - mae: 39.1538 - 12ms/epoch - 921us/step
Epoch 400/500
13/13 - 0s - loss: 2421.8564 - mae: 38.6866 - 12ms/epoch - 921us/step
Epoch 401/500
13/13 - 0s - loss: 2513.2737 - mae: 39.3137 - 11ms/epoch - 844us/step
Epoch 402/500
13/13 - 0s - loss: 2475.2676 - mae: 39.3039 - 14ms/epoch - 1ms/step
Epoch 403/500
13/13 - 0s - loss: 2410.8821 - mae: 38.6788 - 12ms/epoch - 921us/step
Epoch 404/500
13/13 - 0s - loss: 2397.1748 - mae: 38.4604 - 12ms/epoch - 921us/step
Epoch 405/500
13/13 - 0s - loss: 2401.1748 - mae: 38.5868 - 12ms/epoch - 921us/step
Epoch 406/500
13/13 - 0s - loss: 2395.6621 - mae: 38.5002 - 12ms/epoch - 921us/s

Epoch 493/500
13/13 - 0s - loss: 2362.7058 - mae: 37.9779 - 10ms/epoch - 767us/step
Epoch 494/500
13/13 - 0s - loss: 2348.6731 - mae: 37.8190 - 11ms/epoch - 844us/step
Epoch 495/500
13/13 - 0s - loss: 2343.6809 - mae: 37.6890 - 10ms/epoch - 767us/step
Epoch 496/500
13/13 - 0s - loss: 2347.7971 - mae: 37.6895 - 10ms/epoch - 767us/step
Epoch 497/500
13/13 - 0s - loss: 2388.5935 - mae: 38.0016 - 12ms/epoch - 921us/step
Epoch 498/500
13/13 - 0s - loss: 2387.8496 - mae: 38.3746 - 11ms/epoch - 844us/step
Epoch 499/500
13/13 - 0s - loss: 2336.3813 - mae: 37.8706 - 11ms/epoch - 844us/step
Epoch 500/500
13/13 - 0s - loss: 2422.1174 - mae: 38.3645 - 13ms/epoch - 997us/step


In [16]:
#평가비교해보자
eval_test = model.evaluate(X_test, y_test)
eval_test

2/2 [==============================] - 0s 2ms/step - loss: 3167.1184 - mae: 44.7759


[3167.118408203125, 44.775943756103516]

In [17]:
pred_test = model.predict(X_test)
pred_test[:5]

array([[113.2446  ],
       [ 76.431725],
       [153.16464 ],
       [189.44379 ],
       [ 65.18048 ]], dtype=float32)

In [18]:
y_test[:5]

array([ 79.,  55., 109., 178.,  39.])

In [19]:
#R2는 1에 가까울수록 좋다.
from sklearn.metrics import r2_score
R2 = r2_score(y_test, pred_test, multioutput='variance_weighted')
R2

0.5695508566147223